version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: financeflow-db
    environment:
      POSTGRES_DB: financeflow
      POSTGRES_USER: financeflow
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - financeflow-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: financeflow-server
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://financeflow:password123@postgres:5432/financeflow
      PASSWORD: financeflow123
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - financeflow-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: financeflow-client
    environment:
      VITE_API_URL: http://localhost:5000
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - financeflow-network

volumes:
  postgres_data:

networks:
  financeflow-network:
    driver: bridge