version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: finanztracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/config/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: